### xxl-job email
xxl:
  job:
    mail:
      host: smtp.163.com
      port: 25
      ssl: false
      username: ovono802302@163.com
      password: asdfzxcv
      sendNick: 《任务调度平台XXL-JOB》
    login:
      username: admin
      password: 123456
    i18n:
    accessToken:


server:
  servlet:
    context-path: /


spring:
    freemarker:
#      check-template-location: false
      prefix:
      suffix: .ftl
      content-type: text/html;charset=UTF-8
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request
      expose-spring-macro-helpers: true
      cache: true
      template-loader-path: classpath:/webapp
    profiles:
        active: env
    thymeleaf:
        cache: false
        mode: LEGACYHTML5
        prefix: classpath:/
    # jackson时间格式化
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
#    http:
#        multipart:
#            max-file-size: 100MB
#            max-request-size: 100MB
#            enabled: true
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,classpath:/templates/,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/,classpath:/webapp/,classpath:/
#    cache:
#      type: redis
#    redis:
#        open: true  # 是否开启redis缓存  true开启   false关闭
#        host: 192.168.5.30
#        port: 6379
#        timeout: 6000  # 连接超时时长（毫秒）
#        pool:
#            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#            max-idle: 10      # 连接池中的最大空闲连接
#            min-idle: 5       # 连接池中的最小空闲连接
    datasource:
        url: jdbc:mysql://192.168.5.30:3306/xxl_job?useUnicode=true&characterEncoding=utf-8&useSSL=false
        password: zhonglixuntaqianbaidu
        username: root
        driver-class-name: com.mysql.jdbc.Driver
        tomcat:
          initial-size: 1
          max-active: 5
          max-wait: 1000
          min-idle: 1
          max-idle: 4
    #mail:
      #default-encoding: UTF-8
      #host: smtp.gmail.com
      #username: opssysadm@gmail.com
      #password: Eveb5290
      #port: 465
      #protocol: smtp
      #test-connection: false
# Mybatis配置
mybatis:
    mapperLocations: classpath:mybatis-mapper/*.xml
#    configLocation: classpath:mybatis.xml