server:
  rootPath: /
  staticPath: /
#  context-path: /

spring:
    profiles:
        active: env
    thymeleaf:
        cache: false
        mode: LEGACYHTML5
        prefix: classpath:/templates
    # jackson时间格式化
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
#    http:
#        multipart:
#            max-file-size: 100MB
#            max-request-size: 100MB
#            enabled: true
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,classpath:/templates/,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/
    cache:
      type: redis
#    redis:
#        open: true  # 是否开启redis缓存  true开启   false关闭
#        host: 192.168.5.30
#        port: 6379
#        timeout: 6000  # 连接超时时长（毫秒）
#        pool:
#            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#            max-idle: 10      # 连接池中的最大空闲连接
#            min-idle: 5       # 连接池中的最小空闲连接
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
        url: jdbc:mysql://192.168.5.30:3306/xxl-job?useUnicode=true&characterEncoding=UTF-8
        password: zhonglixundaqianbaidu
        username: root
    #mail:
      #default-encoding: UTF-8
      #host: smtp.gmail.com
      #username: opssysadm@gmail.com
      #password: Eveb5290
      #port: 465
      #protocol: smtp
      #test-connection: false
# Mybatis配置
mybatis:
    mapperLocations: classpath:mybatis-mapper/*.xml
#    configLocation: classpath:mybatis.xml